# Workflow name
name: testing-sentiment-analyzer-actions

# Name of event which trigger the workflow 
on: 
  pull_request:
    # Pull request events on develop branch
    branches:
      - develop

# Workflow jobs
jobs:
  api-unit-test: 
    runs-on: ubuntu-latest
    #All steps running on api-unit-test job
    steps: 
      #Checkout the git repository and workflow can access it
      - uses: actions/checkout@v2         
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install project dependencies
        run: poetry install
      - name: Launch unit test with pytest
        id: test
        run: poetry run python -m pytest ./tests/unit/
 
  
  
